DROP DATABASE IF EXISTS CEVICHERIA;
CREATE DATABASE CEVICHERIA;
USE CEVICHERIA;

CREATE TABLE USUARIO (
    IDUSUARIO INT AUTO_INCREMENT, 
    NOMBRES VARCHAR(50), 
    APELLIDOS VARCHAR(60), 
    EMAIL VARCHAR(50), 
    CONTRASEÑA VARCHAR(30), 
    PRIMARY KEY (IDUSUARIO)
);

CREATE TABLE RESERVAS (
    IDRESERVA INT AUTO_INCREMENT, 
    FECHA DATE, 
    HORA TIME, 
    PERSONAS INT, 
    DETALLES VARCHAR(120), 
    IDUSUARIO INT, 
    PRIMARY KEY (IDRESERVA), 
    FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)
);